# Generated by Django 6.1.1 on 2026-09-23 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_alter_category_options'),
        ('members', '0002_alter_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('return_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('brrowed', 'Brrowed'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='brrowed', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='books.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='members.member')),
            ],
        ),
    ]
