# Generated by Django 6.1.1 on 2026-09-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowing',
            old_name='return_at',
            new_name='returned_at',
        ),
    ]
