# Generated by Django 6.1.1 on 2026-09-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0002_rename_return_at_borrowing_returned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('brrowed', 'Brrowed'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
