# Generated by Django 6.1.1 on 2026-09-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id']},
        ),
    ]
